# Server configuration
server:
  port: 8080

# Spring configuration

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:  
    url : jdbc:mysql://localhost:3306/deep_stroll?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username : 
    password : 
    driverClassName : com.mysql.cj.jdbc.Driver
    
#Mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.mbry.IronMan.entity

# JWT
jwt:
  header: 
  secret: 
  expiration: 
  tokenHead: 
  supercode: 
  route:
    authentication:
      path: /api/login/
      register: /api/user/register/

# Tencent Cos
tencent:
  cos:
    secretId: 
    secretKey: 
    region: 
    bucket:  

# 
aliyun:
  access-key-id: 
  access-key-secret: 
  sign-name: 
  template-code: 