# Server configuration
server:
  port: 8080

# Spring configuration
spring:
  datasource:  
    url : jdbc:mysql://localhost:3306/deep_stroll?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password : root
    driverClassName : com.mysql.cj.jdbc.Driver
    
#Mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.mbry.IronMan.entity